---
title: "Preface and Acknowledgments"
output: pdf_document
---

# Preface
This book is a companion to __Quantitative Research Methods for Political Science, Public Policy and Public Administration (With Applications in R): 3rd Edition__, an open-source text book that is available here (\url{https://hdl.handle.net/11244/52244}). It grew from our experiences teaching introductory and intermediate quantitative methods classes for graduate students in Political Science and Public Policy at the University of Oklahoma. We teach these courses using a lab format that pairs seminars on theory and statistics with lab exercises that focus on applications in R. We use the text book to motivate seminars and this book to guide lab exercises. The book is written in `R Markdown` and `bookdown`. While a "complete" copy of the book is available, we suggest that students and instructors use the "raw" `.Rmd` files for lab exercises. These materials ara available in our `GitHub` repository, here: \url{https://github.com/ripberjt/qrmlabs}. 






Students can download as a free PDF, and to couple it with \texttt{R}, an open-source (free) statistical program, and data from the Meso-Scale Integrated Socio-geographic Network (M-SISNet), a quarterly survey of approximately 1,500 households in Oklahoma that is conducted with support of the National Science Foundation (Grant No. IIA-1301789). Readers can learn about and download the data at \url{http://crcm.ou.edu/epscordata/}.







By intent, this book represents an open-ended group project that changes over time as new ideas and new instructors become involved in teaching graduate methods in the University of Oklahoma Political Science Department. The first edition of the book grew from lecture notes and slides that Hank Jenkins-Smith used in his methods classes. The second edition was amended to encompass material from Gary Copeland’s introductory graduate methods classes. The third edition (this one!) was updated by Joseph Ripberger, who currently manages and uses the book in his introductory and intermediate quantitative methods courses for Ph.D. students in the University of Oklahoma Political Science Department.

In addition to instructors, the graduate assistants who co-instruct the methods courses are an essential part of the authorship team. The tradition started with Dr. Matthew Nowlin, who assisted in drafting the first edition in \LaTeX. Dr. Tyler Hughes and Aaron Fister were instrumental in implementing the changes for the second edition. Wesley Wehde, the current co-instructor, is responsible for much of the third edition. 

This book, like politics and policy, constantly changes. Keep an eye on our \texttt{GitHub} repository (\url{https://github.com/ripberjt/qrmtextbook}) for modifications and additions. You never know what you might find peering back at you.\\

\noindent Hank Jenkins-Smith\\
Joseph Ripberger\\
Gary Copeland\\
Matthew Nowlin\\
Tyler Hughes\\
Aaron Fister\\
Wesley Wehde\\
