<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Covariance and Correlation | Lab Guide to Quantitative Research Methods in Political Science, Public Policy &amp; Public Administration.</title>
  <meta name="description" content="7 Covariance and Correlation | Lab Guide to Quantitative Research Methods in Political Science, Public Policy &amp; Public Administration." />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Covariance and Correlation | Lab Guide to Quantitative Research Methods in Political Science, Public Policy &amp; Public Administration." />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Covariance and Correlation | Lab Guide to Quantitative Research Methods in Political Science, Public Policy &amp; Public Administration." />
  
  
  

<meta name="author" content="Joseph Ripberger, Cody Adams, Alex Davis, and Josie Davis" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="inference-for-two-populations.html">
<link rel="next" href="bivariate-linear-regression.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.46.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.46.1/plotly-latest.min.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#requirements"><i class="fa fa-check"></i>Requirements</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html"><i class="fa fa-check"></i><b>1</b> Introduction to R, RStudio, and R Markdown</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#introduction-to-r-the-language"><i class="fa fa-check"></i><b>1.1</b> Introduction to R, the language</a><ul>
<li class="chapter" data-level="1.1.1" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#benefits-of-r"><i class="fa fa-check"></i><b>1.1.1</b> Benefits of R</a></li>
<li class="chapter" data-level="1.1.2" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#packages"><i class="fa fa-check"></i><b>1.1.2</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#rsudio"><i class="fa fa-check"></i><b>1.2</b> RSudio</a><ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#navigating-rstudio"><i class="fa fa-check"></i><b>1.2.1</b> Navigating RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#r-markdown"><i class="fa fa-check"></i><b>1.3</b> R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basics-of-r.html"><a href="basics-of-r.html"><i class="fa fa-check"></i><b>2</b> Basics of R</a><ul>
<li class="chapter" data-level="2.1" data-path="basics-of-r.html"><a href="basics-of-r.html#r-as-a-calculator"><i class="fa fa-check"></i><b>2.1</b> R, as a Calculator</a><ul>
<li class="chapter" data-level="2.1.1" data-path="basics-of-r.html"><a href="basics-of-r.html#order-of-operations"><i class="fa fa-check"></i><b>2.1.1</b> Order of Operations</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="basics-of-r.html"><a href="basics-of-r.html#objects"><i class="fa fa-check"></i><b>2.2</b> Objects</a></li>
<li class="chapter" data-level="2.3" data-path="basics-of-r.html"><a href="basics-of-r.html#functions"><i class="fa fa-check"></i><b>2.3</b> Functions</a><ul>
<li class="chapter" data-level="2.3.1" data-path="basics-of-r.html"><a href="basics-of-r.html#object-types"><i class="fa fa-check"></i><b>2.3.1</b> Object Types</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="basics-of-r.html"><a href="basics-of-r.html#packages-1"><i class="fa fa-check"></i><b>2.4</b> Packages</a><ul>
<li class="chapter" data-level="2.4.1" data-path="basics-of-r.html"><a href="basics-of-r.html#installing-packages"><i class="fa fa-check"></i><b>2.4.1</b> Installing Packages</a></li>
<li class="chapter" data-level="2.4.2" data-path="basics-of-r.html"><a href="basics-of-r.html#loading-packages"><i class="fa fa-check"></i><b>2.4.2</b> Loading Packages</a></li>
<li class="chapter" data-level="2.4.3" data-path="basics-of-r.html"><a href="basics-of-r.html#updating-packages"><i class="fa fa-check"></i><b>2.4.3</b> Updating Packages</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="basics-of-r.html"><a href="basics-of-r.html#r-help"><i class="fa fa-check"></i><b>2.5</b> R Help</a></li>
<li class="chapter" data-level="2.6" data-path="basics-of-r.html"><a href="basics-of-r.html#setting-a-working-directory"><i class="fa fa-check"></i><b>2.6</b> Setting a Working Directory</a></li>
<li class="chapter" data-level="2.7" data-path="basics-of-r.html"><a href="basics-of-r.html#importing-your-data"><i class="fa fa-check"></i><b>2.7</b> Importing Your Data</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="formatting-describing-and-visualizing-data.html"><a href="formatting-describing-and-visualizing-data.html"><i class="fa fa-check"></i><b>3</b> Formatting, Describing, and Visualizing Data</a><ul>
<li class="chapter" data-level="3.1" data-path="formatting-describing-and-visualizing-data.html"><a href="formatting-describing-and-visualizing-data.html#factoring"><i class="fa fa-check"></i><b>3.1</b> Factoring</a><ul>
<li class="chapter" data-level="3.1.1" data-path="formatting-describing-and-visualizing-data.html"><a href="formatting-describing-and-visualizing-data.html#coerce-factoring"><i class="fa fa-check"></i><b>3.1.1</b> Coerce Factoring</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="formatting-describing-and-visualizing-data.html"><a href="formatting-describing-and-visualizing-data.html#recoding"><i class="fa fa-check"></i><b>3.2</b> Recoding</a><ul>
<li class="chapter" data-level="3.2.1" data-path="formatting-describing-and-visualizing-data.html"><a href="formatting-describing-and-visualizing-data.html#factoring-and-recoding"><i class="fa fa-check"></i><b>3.2.1</b> Factoring and Recoding</a></li>
<li class="chapter" data-level="3.2.2" data-path="formatting-describing-and-visualizing-data.html"><a href="formatting-describing-and-visualizing-data.html#creating-a-dummy-variable"><i class="fa fa-check"></i><b>3.2.2</b> Creating a Dummy Variable</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="formatting-describing-and-visualizing-data.html"><a href="formatting-describing-and-visualizing-data.html#part-iii-building-and-sorting-your-data"><i class="fa fa-check"></i><b>3.3</b> Part III: Building and Sorting Your Data</a><ul>
<li class="chapter" data-level="3.3.1" data-path="formatting-describing-and-visualizing-data.html"><a href="formatting-describing-and-visualizing-data.html#the-tidyverse"><i class="fa fa-check"></i><b>3.3.1</b> The Tidyverse</a></li>
<li class="chapter" data-level="3.3.2" data-path="formatting-describing-and-visualizing-data.html"><a href="formatting-describing-and-visualizing-data.html#other-methods-of-exploring-your-data"><i class="fa fa-check"></i><b>3.3.2</b> Other Methods of Exploring Your Data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="formatting-describing-and-visualizing-data.html"><a href="formatting-describing-and-visualizing-data.html#working-with-nominal-data"><i class="fa fa-check"></i><b>3.4</b> Working with Nominal Data</a><ul>
<li class="chapter" data-level="3.4.1" data-path="formatting-describing-and-visualizing-data.html"><a href="formatting-describing-and-visualizing-data.html#finding-the-mode"><i class="fa fa-check"></i><b>3.4.1</b> Finding the Mode</a></li>
<li class="chapter" data-level="3.4.2" data-path="formatting-describing-and-visualizing-data.html"><a href="formatting-describing-and-visualizing-data.html#visualizing-nominal-data"><i class="fa fa-check"></i><b>3.4.2</b> Visualizing Nominal Data</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="formatting-describing-and-visualizing-data.html"><a href="formatting-describing-and-visualizing-data.html#working-with-ordinal-data"><i class="fa fa-check"></i><b>3.5</b> Working with Ordinal Data</a></li>
<li class="chapter" data-level="3.6" data-path="formatting-describing-and-visualizing-data.html"><a href="formatting-describing-and-visualizing-data.html#working-with-interval-data"><i class="fa fa-check"></i><b>3.6</b> Working with Interval Data</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="visualizing-data-probability-the-normal-distribution-and-z-scores.html"><a href="visualizing-data-probability-the-normal-distribution-and-z-scores.html"><i class="fa fa-check"></i><b>4</b> Visualizing Data, Probability, the Normal Distribution, and Z Scores</a><ul>
<li class="chapter" data-level="4.1" data-path="visualizing-data-probability-the-normal-distribution-and-z-scores.html"><a href="visualizing-data-probability-the-normal-distribution-and-z-scores.html#histograms-and-density"><i class="fa fa-check"></i><b>4.1</b> Histograms and Density</a><ul>
<li class="chapter" data-level="4.1.1" data-path="visualizing-data-probability-the-normal-distribution-and-z-scores.html"><a href="visualizing-data-probability-the-normal-distribution-and-z-scores.html#normal-distribution-and-histograms"><i class="fa fa-check"></i><b>4.1.1</b> Normal Distribution and Histograms</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="visualizing-data-probability-the-normal-distribution-and-z-scores.html"><a href="visualizing-data-probability-the-normal-distribution-and-z-scores.html#probability-and-distributions"><i class="fa fa-check"></i><b>4.2</b> Probability and Distributions</a></li>
<li class="chapter" data-level="4.3" data-path="visualizing-data-probability-the-normal-distribution-and-z-scores.html"><a href="visualizing-data-probability-the-normal-distribution-and-z-scores.html#visualizing-normality"><i class="fa fa-check"></i><b>4.3</b> Visualizing Normality</a></li>
<li class="chapter" data-level="4.4" data-path="visualizing-data-probability-the-normal-distribution-and-z-scores.html"><a href="visualizing-data-probability-the-normal-distribution-and-z-scores.html#z-scores"><i class="fa fa-check"></i><b>4.4</b> Z-Scores</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="foundations-for-inference.html"><a href="foundations-for-inference.html"><i class="fa fa-check"></i><b>5</b> Foundations for Inference</a><ul>
<li class="chapter" data-level="5.1" data-path="foundations-for-inference.html"><a href="foundations-for-inference.html#testing-for-normality"><i class="fa fa-check"></i><b>5.1</b> Testing for Normality</a><ul>
<li class="chapter" data-level="5.1.1" data-path="foundations-for-inference.html"><a href="foundations-for-inference.html#shapiro-wilk-test"><i class="fa fa-check"></i><b>5.1.1</b> Shapiro-Wilk Test</a></li>
<li class="chapter" data-level="5.1.2" data-path="foundations-for-inference.html"><a href="foundations-for-inference.html#testing-normality"><i class="fa fa-check"></i><b>5.1.2</b> Testing Normality</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="foundations-for-inference.html"><a href="foundations-for-inference.html#standard-errors"><i class="fa fa-check"></i><b>5.2</b> Standard Errors</a></li>
<li class="chapter" data-level="5.3" data-path="foundations-for-inference.html"><a href="foundations-for-inference.html#confidence-intervals"><i class="fa fa-check"></i><b>5.3</b> Confidence Intervals</a></li>
<li class="chapter" data-level="5.4" data-path="foundations-for-inference.html"><a href="foundations-for-inference.html#more-on-single-sample-t-tests"><i class="fa fa-check"></i><b>5.4</b> More on Single Sample T-tests</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inference-for-two-populations.html"><a href="inference-for-two-populations.html"><i class="fa fa-check"></i><b>6</b> Inference for Two Populations</a><ul>
<li class="chapter" data-level="6.1" data-path="inference-for-two-populations.html"><a href="inference-for-two-populations.html#proportions"><i class="fa fa-check"></i><b>6.1</b> Proportions</a><ul>
<li class="chapter" data-level="6.1.1" data-path="inference-for-two-populations.html"><a href="inference-for-two-populations.html#two-populations"><i class="fa fa-check"></i><b>6.1.1</b> Two Populations</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="inference-for-two-populations.html"><a href="inference-for-two-populations.html#cross-tabulations"><i class="fa fa-check"></i><b>6.2</b> Cross Tabulations</a><ul>
<li class="chapter" data-level="6.2.1" data-path="inference-for-two-populations.html"><a href="inference-for-two-populations.html#other-coefficients"><i class="fa fa-check"></i><b>6.2.1</b> Other Coefficients</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="inference-for-two-populations.html"><a href="inference-for-two-populations.html#independent-t-tests"><i class="fa fa-check"></i><b>6.3</b> Independent t-tests</a><ul>
<li class="chapter" data-level="6.3.1" data-path="inference-for-two-populations.html"><a href="inference-for-two-populations.html#other-independent-sample-tests"><i class="fa fa-check"></i><b>6.3.1</b> Other Independent Sample Tests</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="inference-for-two-populations.html"><a href="inference-for-two-populations.html#paired-t-test"><i class="fa fa-check"></i><b>6.4</b> Paired t-test</a></li>
<li class="chapter" data-level="6.5" data-path="inference-for-two-populations.html"><a href="inference-for-two-populations.html#visualizing-differences-in-means"><i class="fa fa-check"></i><b>6.5</b> Visualizing Differences in Means</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="covariance-and-correlation.html"><a href="covariance-and-correlation.html"><i class="fa fa-check"></i><b>7</b> Covariance and Correlation</a><ul>
<li class="chapter" data-level="7.1" data-path="covariance-and-correlation.html"><a href="covariance-and-correlation.html#covariance"><i class="fa fa-check"></i><b>7.1</b> Covariance</a><ul>
<li class="chapter" data-level="7.1.1" data-path="covariance-and-correlation.html"><a href="covariance-and-correlation.html#covariance-by-hand"><i class="fa fa-check"></i><b>7.1.1</b> Covariance by Hand</a></li>
<li class="chapter" data-level="7.1.2" data-path="covariance-and-correlation.html"><a href="covariance-and-correlation.html#covariance-in-r"><i class="fa fa-check"></i><b>7.1.2</b> Covariance in R</a></li>
<li class="chapter" data-level="7.1.3" data-path="covariance-and-correlation.html"><a href="covariance-and-correlation.html#covariance-in-class-data-set"><i class="fa fa-check"></i><b>7.1.3</b> Covariance in Class Data Set</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="covariance-and-correlation.html"><a href="covariance-and-correlation.html#correlation"><i class="fa fa-check"></i><b>7.2</b> Correlation</a><ul>
<li class="chapter" data-level="7.2.1" data-path="covariance-and-correlation.html"><a href="covariance-and-correlation.html#correlation-by-hand"><i class="fa fa-check"></i><b>7.2.1</b> Correlation by Hand</a></li>
<li class="chapter" data-level="7.2.2" data-path="covariance-and-correlation.html"><a href="covariance-and-correlation.html#correlation-tests"><i class="fa fa-check"></i><b>7.2.2</b> Correlation Tests</a></li>
<li class="chapter" data-level="7.2.3" data-path="covariance-and-correlation.html"><a href="covariance-and-correlation.html#correlation-across-groups"><i class="fa fa-check"></i><b>7.2.3</b> Correlation Across Groups</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="covariance-and-correlation.html"><a href="covariance-and-correlation.html#visualizing-correlation"><i class="fa fa-check"></i><b>7.3</b> Visualizing Correlation</a><ul>
<li class="chapter" data-level="7.3.1" data-path="covariance-and-correlation.html"><a href="covariance-and-correlation.html#another-example-political-party"><i class="fa fa-check"></i><b>7.3.1</b> Another Example: Political Party</a></li>
<li class="chapter" data-level="7.3.2" data-path="covariance-and-correlation.html"><a href="covariance-and-correlation.html#one-more-visualization"><i class="fa fa-check"></i><b>7.3.2</b> One More Visualization</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="bivariate-linear-regression.html"><a href="bivariate-linear-regression.html"><i class="fa fa-check"></i><b>8</b> Bivariate Linear Regression</a><ul>
<li class="chapter" data-level="8.1" data-path="bivariate-linear-regression.html"><a href="bivariate-linear-regression.html#bivariate-linear-regression-by-hand"><i class="fa fa-check"></i><b>8.1</b> Bivariate Linear Regression by Hand</a><ul>
<li class="chapter" data-level="8.1.1" data-path="bivariate-linear-regression.html"><a href="bivariate-linear-regression.html#calculating-goodness-of-fit"><i class="fa fa-check"></i><b>8.1.1</b> Calculating Goodness of Fit</a></li>
<li class="chapter" data-level="8.1.2" data-path="bivariate-linear-regression.html"><a href="bivariate-linear-regression.html#checking-our-work"><i class="fa fa-check"></i><b>8.1.2</b> Checking Our Work</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="bivariate-linear-regression.html"><a href="bivariate-linear-regression.html#bivariate-regression-in-r"><i class="fa fa-check"></i><b>8.2</b> Bivariate Regression in R</a></li>
<li class="chapter" data-level="8.3" data-path="bivariate-linear-regression.html"><a href="bivariate-linear-regression.html#the-residuals"><i class="fa fa-check"></i><b>8.3</b> The Residuals</a></li>
<li class="chapter" data-level="8.4" data-path="bivariate-linear-regression.html"><a href="bivariate-linear-regression.html#comparing-models"><i class="fa fa-check"></i><b>8.4</b> Comparing Models</a><ul>
<li class="chapter" data-level="8.4.1" data-path="bivariate-linear-regression.html"><a href="bivariate-linear-regression.html#visualizing-multiple-models"><i class="fa fa-check"></i><b>8.4.1</b> Visualizing Multiple Models</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="bivariate-linear-regression.html"><a href="bivariate-linear-regression.html#hypothesis-testing"><i class="fa fa-check"></i><b>8.5</b> Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="multivariable-linear-regression.html"><a href="multivariable-linear-regression.html"><i class="fa fa-check"></i><b>9</b> Multivariable Linear Regression</a><ul>
<li class="chapter" data-level="9.1" data-path="multivariable-linear-regression.html"><a href="multivariable-linear-regression.html#calculating-least-squared-estimates"><i class="fa fa-check"></i><b>9.1</b> Calculating Least-Squared Estimates</a><ul>
<li class="chapter" data-level="9.1.1" data-path="multivariable-linear-regression.html"><a href="multivariable-linear-regression.html#matrix-algebra"><i class="fa fa-check"></i><b>9.1.1</b> Matrix Algebra</a></li>
<li class="chapter" data-level="9.1.2" data-path="multivariable-linear-regression.html"><a href="multivariable-linear-regression.html#representing-system-of-linear-equations-as-matrices"><i class="fa fa-check"></i><b>9.1.2</b> Representing System of Linear Equations as Matrices</a></li>
<li class="chapter" data-level="9.1.3" data-path="multivariable-linear-regression.html"><a href="multivariable-linear-regression.html#ols-regression-and-matrices"><i class="fa fa-check"></i><b>9.1.3</b> OLS Regression and Matrices</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="multivariable-linear-regression.html"><a href="multivariable-linear-regression.html#multiple-regression-in-r"><i class="fa fa-check"></i><b>9.2</b> Multiple Regression in R</a></li>
<li class="chapter" data-level="9.3" data-path="multivariable-linear-regression.html"><a href="multivariable-linear-regression.html#hypothesis-testing-with-multivariable-regression"><i class="fa fa-check"></i><b>9.3</b> Hypothesis Testing with Multivariable Regression</a><ul>
<li class="chapter" data-level="9.3.1" data-path="multivariable-linear-regression.html"><a href="multivariable-linear-regression.html#visualizing-multivariable-linear-regression"><i class="fa fa-check"></i><b>9.3.1</b> Visualizing Multivariable Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="multivariable-linear-regression.html"><a href="multivariable-linear-regression.html#predicting-with-ols-regression"><i class="fa fa-check"></i><b>9.4</b> Predicting with OLS Regression</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="categorical-explanatory-variables-dummy-variables-and-interactions.html"><a href="categorical-explanatory-variables-dummy-variables-and-interactions.html"><i class="fa fa-check"></i><b>10</b> Categorical Explanatory Variables, Dummy Variables, and Interactions</a><ul>
<li class="chapter" data-level="10.1" data-path="categorical-explanatory-variables-dummy-variables-and-interactions.html"><a href="categorical-explanatory-variables-dummy-variables-and-interactions.html#dummy-variables"><i class="fa fa-check"></i><b>10.1</b> Dummy Variables</a><ul>
<li class="chapter" data-level="10.1.1" data-path="categorical-explanatory-variables-dummy-variables-and-interactions.html"><a href="categorical-explanatory-variables-dummy-variables-and-interactions.html#multiple-dummy-variables"><i class="fa fa-check"></i><b>10.1.1</b> Multiple Dummy Variables</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="categorical-explanatory-variables-dummy-variables-and-interactions.html"><a href="categorical-explanatory-variables-dummy-variables-and-interactions.html#interactions"><i class="fa fa-check"></i><b>10.2</b> Interactions</a><ul>
<li class="chapter" data-level="10.2.1" data-path="categorical-explanatory-variables-dummy-variables-and-interactions.html"><a href="categorical-explanatory-variables-dummy-variables-and-interactions.html#interactions-with-two-non-binary-variables"><i class="fa fa-check"></i><b>10.2.1</b> Interactions with Two Non-binary Variables</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="categorical-explanatory-variables-dummy-variables-and-interactions.html"><a href="categorical-explanatory-variables-dummy-variables-and-interactions.html#releveling-variables"><i class="fa fa-check"></i><b>10.3</b> Releveling Variables</a></li>
<li class="chapter" data-level="10.4" data-path="categorical-explanatory-variables-dummy-variables-and-interactions.html"><a href="categorical-explanatory-variables-dummy-variables-and-interactions.html#interaction-plots"><i class="fa fa-check"></i><b>10.4</b> Interaction Plots</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="non-linearity-non-normality-and-multicollinearity.html"><a href="non-linearity-non-normality-and-multicollinearity.html"><i class="fa fa-check"></i><b>11</b> Non-linearity, Non-normality, and Multicollinearity</a><ul>
<li class="chapter" data-level="11.1" data-path="non-linearity-non-normality-and-multicollinearity.html"><a href="non-linearity-non-normality-and-multicollinearity.html#non-linearity"><i class="fa fa-check"></i><b>11.1</b> Non-linearity</a><ul>
<li class="chapter" data-level="11.1.1" data-path="non-linearity-non-normality-and-multicollinearity.html"><a href="non-linearity-non-normality-and-multicollinearity.html#exploring-non-linearity"><i class="fa fa-check"></i><b>11.1.1</b> Exploring Non-linearity</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="non-linearity-non-normality-and-multicollinearity.html"><a href="non-linearity-non-normality-and-multicollinearity.html#non-normality"><i class="fa fa-check"></i><b>11.2</b> Non-normality</a></li>
<li class="chapter" data-level="11.3" data-path="non-linearity-non-normality-and-multicollinearity.html"><a href="non-linearity-non-normality-and-multicollinearity.html#multicollinearity"><i class="fa fa-check"></i><b>11.3</b> Multicollinearity</a></li>
<li class="chapter" data-level="11.4" data-path="non-linearity-non-normality-and-multicollinearity.html"><a href="non-linearity-non-normality-and-multicollinearity.html#standardizing-coefficients"><i class="fa fa-check"></i><b>11.4</b> Standardizing Coefficients</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="diagnosing-and-addressing-problems-in-linear-regression.html"><a href="diagnosing-and-addressing-problems-in-linear-regression.html"><i class="fa fa-check"></i><b>12</b> Diagnosing and Addressing Problems in Linear Regression</a><ul>
<li class="chapter" data-level="12.1" data-path="diagnosing-and-addressing-problems-in-linear-regression.html"><a href="diagnosing-and-addressing-problems-in-linear-regression.html#introduction-to-the-data"><i class="fa fa-check"></i><b>12.1</b> Introduction to the Data</a></li>
<li class="chapter" data-level="12.2" data-path="diagnosing-and-addressing-problems-in-linear-regression.html"><a href="diagnosing-and-addressing-problems-in-linear-regression.html#outliers"><i class="fa fa-check"></i><b>12.2</b> Outliers</a></li>
<li class="chapter" data-level="12.3" data-path="diagnosing-and-addressing-problems-in-linear-regression.html"><a href="diagnosing-and-addressing-problems-in-linear-regression.html#heteroscedasticity"><i class="fa fa-check"></i><b>12.3</b> Heteroscedasticity</a></li>
<li class="chapter" data-level="12.4" data-path="diagnosing-and-addressing-problems-in-linear-regression.html"><a href="diagnosing-and-addressing-problems-in-linear-regression.html#revisiting-linearity"><i class="fa fa-check"></i><b>12.4</b> Revisiting Linearity</a><ul>
<li class="chapter" data-level="12.4.1" data-path="diagnosing-and-addressing-problems-in-linear-regression.html"><a href="diagnosing-and-addressing-problems-in-linear-regression.html#normality"><i class="fa fa-check"></i><b>12.4.1</b> Normality</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>13</b> Logistic Regression</a><ul>
<li class="chapter" data-level="13.1" data-path="logistic-regression.html"><a href="logistic-regression.html#logistic-regression-with-a-binary-dv"><i class="fa fa-check"></i><b>13.1</b> Logistic Regression with a Binary DV</a><ul>
<li class="chapter" data-level="13.1.1" data-path="logistic-regression.html"><a href="logistic-regression.html#goodness-of-fit-logit-regression"><i class="fa fa-check"></i><b>13.1.1</b> Goodness of Fit, Logit Regression</a></li>
<li class="chapter" data-level="13.1.2" data-path="logistic-regression.html"><a href="logistic-regression.html#percent-correctly-predicted"><i class="fa fa-check"></i><b>13.1.2</b> Percent Correctly Predicted</a></li>
<li class="chapter" data-level="13.1.3" data-path="logistic-regression.html"><a href="logistic-regression.html#logit-regression-with-groups"><i class="fa fa-check"></i><b>13.1.3</b> Logit Regression with Groups</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="logistic-regression.html"><a href="logistic-regression.html#ordered-logit-and-creating-an-index"><i class="fa fa-check"></i><b>13.2</b> Ordered Logit and Creating an Index</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="statistical-simulations.html"><a href="statistical-simulations.html"><i class="fa fa-check"></i><b>14</b> Statistical Simulations</a><ul>
<li class="chapter" data-level="14.1" data-path="statistical-simulations.html"><a href="statistical-simulations.html#the-basics"><i class="fa fa-check"></i><b>14.1</b> The Basics</a><ul>
<li class="chapter" data-level="14.1.1" data-path="statistical-simulations.html"><a href="statistical-simulations.html#plotting-predictions-with-zelig"><i class="fa fa-check"></i><b>14.1.1</b> Plotting Predictions with Zelig</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="statistical-simulations.html"><a href="statistical-simulations.html#other-models"><i class="fa fa-check"></i><b>14.2</b> Other Models</a><ul>
<li class="chapter" data-level="14.2.1" data-path="statistical-simulations.html"><a href="statistical-simulations.html#ordered-logit"><i class="fa fa-check"></i><b>14.2.1</b> Ordered Logit</a></li>
<li class="chapter" data-level="14.2.2" data-path="statistical-simulations.html"><a href="statistical-simulations.html#another-example"><i class="fa fa-check"></i><b>14.2.2</b> Another Example</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="statistical-simulations.html"><a href="statistical-simulations.html#zelig-with-non-zelig-models"><i class="fa fa-check"></i><b>14.3</b> Zelig with non-Zelig Models:</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="appendix-guide-to-data-visualization.html"><a href="appendix-guide-to-data-visualization.html"><i class="fa fa-check"></i><b>15</b> Appendix: Guide to Data Visualization</a><ul>
<li class="chapter" data-level="15.1" data-path="appendix-guide-to-data-visualization.html"><a href="appendix-guide-to-data-visualization.html#deciding-which-visualization-to-use"><i class="fa fa-check"></i><b>15.1</b> Deciding Which Visualization to Use</a><ul>
<li class="chapter" data-level="" data-path="appendix-guide-to-data-visualization.html"><a href="appendix-guide-to-data-visualization.html#for-exploring-a-single-variable"><i class="fa fa-check"></i>For Exploring a Single Variable</a></li>
<li class="chapter" data-level="" data-path="appendix-guide-to-data-visualization.html"><a href="appendix-guide-to-data-visualization.html#for-displaying-two-or-more-variables"><i class="fa fa-check"></i>For Displaying Two (or more) Variables</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="appendix-guide-to-data-visualization.html"><a href="appendix-guide-to-data-visualization.html#adding-labels"><i class="fa fa-check"></i><b>15.2</b> Adding Labels</a></li>
<li class="chapter" data-level="15.3" data-path="appendix-guide-to-data-visualization.html"><a href="appendix-guide-to-data-visualization.html#scale-and-limits"><i class="fa fa-check"></i><b>15.3</b> Scale and Limits</a></li>
<li class="chapter" data-level="15.4" data-path="appendix-guide-to-data-visualization.html"><a href="appendix-guide-to-data-visualization.html#visualizing-error"><i class="fa fa-check"></i><b>15.4</b> Visualizing Error</a><ul>
<li class="chapter" data-level="" data-path="appendix-guide-to-data-visualization.html"><a href="appendix-guide-to-data-visualization.html#confidence-intervals-1"><i class="fa fa-check"></i>Confidence Intervals</a></li>
<li class="chapter" data-level="" data-path="appendix-guide-to-data-visualization.html"><a href="appendix-guide-to-data-visualization.html#error-bars"><i class="fa fa-check"></i>Error Bars</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="appendix-guide-to-data-visualization.html"><a href="appendix-guide-to-data-visualization.html#adding-color"><i class="fa fa-check"></i><b>15.5</b> Adding Color</a></li>
<li class="chapter" data-level="15.6" data-path="appendix-guide-to-data-visualization.html"><a href="appendix-guide-to-data-visualization.html#position-adjustments"><i class="fa fa-check"></i><b>15.6</b> Position Adjustments</a></li>
<li class="chapter" data-level="15.7" data-path="appendix-guide-to-data-visualization.html"><a href="appendix-guide-to-data-visualization.html#using-themes"><i class="fa fa-check"></i><b>15.7</b> Using Themes</a></li>
<li class="chapter" data-level="15.8" data-path="appendix-guide-to-data-visualization.html"><a href="appendix-guide-to-data-visualization.html#putting-it-all-together"><i class="fa fa-check"></i><b>15.8</b> Putting it All Together</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Lab Guide to Quantitative Research Methods in Political Science, Public Policy &amp; Public Administration.</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="covariance-and-correlation" class="section level1">
<h1><span class="header-section-number">7</span> Covariance and Correlation</h1>
<p>Research is not always interested in the contrast of two variables, but oftentimes the relationship of two variables. For instance, what is the relationship between climate science and ideology? The following packages are required for this lab:</p>
<ol style="list-style-type: decimal">
<li>tidyverse</li>
<li>psych</li>
<li>car</li>
<li>vcd</li>
</ol>
<div id="covariance" class="section level2">
<h2><span class="header-section-number">7.1</span> Covariance</h2>
<p>Covariance is the measure of change in one variable associated to change in another variable. That is, the measure of how two random variables vary together.</p>
<p>Calculating covariance of two variables of a known population is trivial, as the product of variation of two variables. However, for samples, covariance is calculated via the following formula:</p>
<p><span class="math display">\[cov(x,y)=\frac{\sum_{i=1}^n (x_{i}-\bar{x})(y_{i}-\bar{y})}{{n-1}}\]</span></p>
<p>Where <code>x</code> and <code>y</code> are two random variables, <code>i</code> is each observation (row), and <code>n</code> is the sample size.</p>
<div id="covariance-by-hand" class="section level3">
<h3><span class="header-section-number">7.1.1</span> Covariance by Hand</h3>
<p>To find covariance by hand, let’s construct a hypothetical data set with variables x and y. We only give each variable three values so that the calculation will be shorter.</p>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb331-1" data-line-number="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">25</span>, <span class="dv">27</span>, <span class="dv">29</span>)</a>
<a class="sourceLine" id="cb331-2" data-line-number="2">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">15</span>, <span class="dv">9</span>)</a></code></pre></div>
<p>First we calculate the difference of each value and the mean for the variables:</p>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb332-1" data-line-number="1">xdev &lt;-<span class="st"> </span>x <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(x)</a>
<a class="sourceLine" id="cb332-2" data-line-number="2">ydev &lt;-<span class="st"> </span>y <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(y)</a></code></pre></div>
<p>Next we find the product of the above differences:</p>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb333-1" data-line-number="1">xdev_ydev &lt;-<span class="st"> </span>xdev <span class="op">*</span><span class="st"> </span>ydev</a>
<a class="sourceLine" id="cb333-2" data-line-number="2">xdev_ydev</a></code></pre></div>
<pre><code>## [1]  9.333333  0.000000 -1.333333</code></pre>
<p>We complete the numerator by finding the sum of the products:</p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb335-1" data-line-number="1">sum_xdev_ydev &lt;-<span class="st"> </span><span class="kw">sum</span>(xdev_ydev)</a></code></pre></div>
<p>Lastly, we complete the covariance calculation by dividing the numerator by the denominator. The denominator is calculated as one less than the sample size:</p>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb336-1" data-line-number="1">cov_xy &lt;-<span class="st"> </span>sum_xdev_ydev <span class="op">/</span><span class="st"> </span>(<span class="dv">3</span> <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb336-2" data-line-number="2">cov_xy</a></code></pre></div>
<pre><code>## [1] 4</code></pre>
</div>
<div id="covariance-in-r" class="section level3">
<h3><span class="header-section-number">7.1.2</span> Covariance in R</h3>
<p>By using the <code>cov()</code> function, R calculates the covariance. We demonstrate the <code>cov()</code> function by confirming the previous section’s calculations:</p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb338-1" data-line-number="1"><span class="kw">cov</span>(x, y)</a></code></pre></div>
<pre><code>## [1] 4</code></pre>
</div>
<div id="covariance-in-class-data-set" class="section level3">
<h3><span class="header-section-number">7.1.3</span> Covariance in Class Data Set</h3>
<p>To demonstrate further we will calculate covariance for various pairs of variables within the class data set. First, suppose we are interested in the relationship between certainty that humans cause climate change (<code>glbcc_cert</code>) and the perceived risk of climate change (<code>glbcc_risk</code>). That is, is there a relationship between respondents’ certainty that humans cause climate change and their perceived risk of climate change? Our hypothesis could be that individuals that are more certain that climate change is a consequence of humans are likely more concerned about the associated risk.</p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb340-1" data-line-number="1"><span class="kw">cov</span>(ds<span class="op">$</span>glbcc_cert, ds<span class="op">$</span>glbcc_risk, <span class="dt">use =</span> <span class="st">&quot;complete.obs&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 3.092168</code></pre>
<p><strong>Note:</strong> The <code>cov()</code> function requires <code>use=&quot;complete.obs&quot;</code> to remove NA entries.</p>
<p>The calculated covariance of certainty and risk perception is positive, indicating the two variables are positively related. As one variable changes, the other variable will change in the same direction with a magnitude of 3.09. Increased certainty that humans cause climate change increases the perceived risk of climate change.</p>
<p>Suppose we are also interested in the relationship of income and perceived risk of climate change:</p>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb342-1" data-line-number="1"><span class="kw">cov</span>(ds<span class="op">$</span>income, ds<span class="op">$</span>glbcc_risk, <span class="dt">use =</span> <span class="st">&quot;complete.obs&quot;</span>)</a></code></pre></div>
<pre><code>## [1] -10826.91</code></pre>
<p>The calculated covariance of income and perceived risk of climate change is negative, indicating the two variables are negatively related. As one variable changes, the other variable will change in the opposite direction with a magnitude of -10826.91.</p>
<p>An important follow-up question is: which variable is more strongly associated to perceived risk, certainty or income? We cannot compare magnitudes to the difference in scales and units. Income is measured on a scale inclusive of higher numbers compared to certainty. To compare strengths of association we need to standardize covariance.</p>
</div>
</div>
<div id="correlation" class="section level2">
<h2><span class="header-section-number">7.2</span> Correlation</h2>
<p>Correlation standardizes covariance on a scale of negative one to one, whereby the magnitude from zero indicates strength of relationship. Similar to covariance, a positive and negative value reflects the respective relationship. The formula for correlation is the following:</p>
<p><span class="math display">\[r_{xy}=\frac{cov(x,y)}{s_xs_y}\]</span></p>
<p>Where x and y are two random variables.</p>
<div id="correlation-by-hand" class="section level3">
<h3><span class="header-section-number">7.2.1</span> Correlation by Hand</h3>
<p>To find covariance by hand, let’s use the data set we constructed earlier to calculate covariance.</p>
<p>Recall we calculated covariance manually via the following steps:</p>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb344-1" data-line-number="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">25</span>, <span class="dv">27</span>, <span class="dv">29</span>)</a>
<a class="sourceLine" id="cb344-2" data-line-number="2">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">15</span>, <span class="dv">9</span>)</a>
<a class="sourceLine" id="cb344-3" data-line-number="3">xdev &lt;-<span class="st"> </span>x <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(x)</a>
<a class="sourceLine" id="cb344-4" data-line-number="4">ydev &lt;-<span class="st"> </span>y <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(y)</a>
<a class="sourceLine" id="cb344-5" data-line-number="5">xdev_ydev &lt;-<span class="st"> </span>xdev <span class="op">*</span><span class="st"> </span>ydev</a>
<a class="sourceLine" id="cb344-6" data-line-number="6">sum_xdev_ydev &lt;-<span class="st"> </span><span class="kw">sum</span>(xdev_ydev)</a>
<a class="sourceLine" id="cb344-7" data-line-number="7">cov_xy &lt;-<span class="st"> </span>(<span class="dv">1</span> <span class="op">/</span><span class="st"> </span>(<span class="dv">3</span> <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)) <span class="op">*</span><span class="st"> </span>sum_xdev_ydev</a>
<a class="sourceLine" id="cb344-8" data-line-number="8">cov_xy</a></code></pre></div>
<pre><code>## [1] 4</code></pre>
<p>For calculating correlation we need the product of the standard deviations of variables <code>x</code> and <code>y</code> for the denominator:</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb346-1" data-line-number="1">stnd.dev &lt;-<span class="st"> </span><span class="kw">sd</span>(x)<span class="op">*</span><span class="kw">sd</span>(y)</a></code></pre></div>
<p>Now we find the quotient of the covariance numerator and standard deviations denominator:</p>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb347-1" data-line-number="1">cov_xy<span class="op">/</span>stnd.dev</a></code></pre></div>
<pre><code>## [1] 0.3973597</code></pre>
<p>The relationship is positive; however, the correlation coefficient is <span class="math inline">\(\approx\)</span> 0.40.</p>
<p>Returning to the class data set, we can find the correlation coefficient for certainty humans cause climate change and perceived risk of climate change from the class data set:</p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb349-1" data-line-number="1">numerator &lt;-<span class="st"> </span><span class="kw">cov</span>(ds<span class="op">$</span>glbcc_cert, ds<span class="op">$</span>glbcc_risk, <span class="dt">use =</span> <span class="st">&quot;complete.obs&quot;</span>)</a>
<a class="sourceLine" id="cb349-2" data-line-number="2">denominator &lt;-<span class="st"> </span><span class="kw">sd</span>(ds<span class="op">$</span>glbcc_cert, <span class="dt">na.rm =</span> T) <span class="op">*</span><span class="st"> </span><span class="kw">sd</span>(ds<span class="op">$</span>glbcc_risk, <span class="dt">na.rm =</span> T)</a>
<a class="sourceLine" id="cb349-3" data-line-number="3">numerator <span class="op">/</span><span class="st"> </span>denominator</a></code></pre></div>
<pre><code>## [1] 0.3699554</code></pre>
<p>The correlation coefficient is <span class="math inline">\(\approx\)</span> 0.37.</p>
<p>Now let’s find the correlation coefficient for ideology and perceived risk from climate change.</p>
<p>First we will create a subset from the class data set <code>ds</code> for the variables of interest, absent of missing observations. <strong>Note:</strong> This subset includes additional variables, <code>f.gender</code> and <code>f.party.2</code> for use later in this lab.</p>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb351-1" data-line-number="1">ds.sub &lt;-<span class="st"> </span>ds <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb351-2" data-line-number="2"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(<span class="st">&quot;glbcc_risk&quot;</span>, <span class="st">&quot;ideol&quot;</span>, <span class="st">&quot;f.gender&quot;</span>, <span class="st">&quot;f.party.2&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb351-3" data-line-number="3"><span class="st">  </span><span class="kw">na.omit</span>()</a></code></pre></div>
<p>The perceived risk and ideology variables are assigned to <code>x</code> and <code>y</code> variables within the <code>ds.sub</code> object, as to follow the formula.</p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb352-1" data-line-number="1">ds.sub<span class="op">$</span>x &lt;-<span class="st"> </span>ds.sub<span class="op">$</span>glbcc_risk</a>
<a class="sourceLine" id="cb352-2" data-line-number="2">ds.sub<span class="op">$</span>y &lt;-<span class="st"> </span>ds.sub<span class="op">$</span>ideol</a></code></pre></div>
<p>The <code>x</code> and <code>y</code> variables are then used to find the covariance, similar to the steps demonstrated earlier:</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb353-1" data-line-number="1">xbar &lt;-<span class="st"> </span><span class="kw">mean</span>(ds.sub<span class="op">$</span>x)</a>
<a class="sourceLine" id="cb353-2" data-line-number="2">ybar &lt;-<span class="st"> </span><span class="kw">mean</span>(ds.sub<span class="op">$</span>y)</a>
<a class="sourceLine" id="cb353-3" data-line-number="3"></a>
<a class="sourceLine" id="cb353-4" data-line-number="4">x.m.xbar &lt;-<span class="st"> </span>ds.sub<span class="op">$</span>x <span class="op">-</span><span class="st"> </span>xbar</a>
<a class="sourceLine" id="cb353-5" data-line-number="5">y.m.ybar &lt;-<span class="st"> </span>ds.sub<span class="op">$</span>y <span class="op">-</span><span class="st"> </span>ybar</a>
<a class="sourceLine" id="cb353-6" data-line-number="6"></a>
<a class="sourceLine" id="cb353-7" data-line-number="7">n &lt;-<span class="st"> </span><span class="kw">length</span>(ds.sub<span class="op">$</span>x)</a>
<a class="sourceLine" id="cb353-8" data-line-number="8">n</a></code></pre></div>
<pre><code>## [1] 2388</code></pre>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb355-1" data-line-number="1">cov.xy &lt;-<span class="st"> </span>(<span class="kw">sum</span>(x.m.xbar <span class="op">*</span><span class="st"> </span>y.m.ybar)) <span class="op">/</span><span class="st"> </span>(n <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb355-2" data-line-number="2">cov.xy</a></code></pre></div>
<pre><code>## [1] -3.134752</code></pre>
<p>Next, we find the correlation coefficient using the covariance as the numerator and the product of both variable standard deviations as the denominator:</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb357-1" data-line-number="1">sd.x &lt;-<span class="st"> </span><span class="kw">sqrt</span>((<span class="kw">sum</span>(x.m.xbar<span class="op">^</span><span class="dv">2</span>)) <span class="op">/</span><span class="st"> </span>(n <span class="op">-</span><span class="st"> </span><span class="dv">1</span>))</a>
<a class="sourceLine" id="cb357-2" data-line-number="2">sd.x</a></code></pre></div>
<pre><code>## [1] 3.058544</code></pre>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb359-1" data-line-number="1">sd.y &lt;-<span class="st"> </span><span class="kw">sqrt</span>((<span class="kw">sum</span>(y.m.ybar<span class="op">^</span><span class="dv">2</span>)) <span class="op">/</span><span class="st"> </span>(n <span class="op">-</span><span class="st"> </span><span class="dv">1</span>))</a>
<a class="sourceLine" id="cb359-2" data-line-number="2">sd.y</a></code></pre></div>
<pre><code>## [1] 1.74181</code></pre>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb361-1" data-line-number="1">sd.xy &lt;-<span class="st"> </span>sd.x<span class="op">*</span>sd.y</a>
<a class="sourceLine" id="cb361-2" data-line-number="2"></a>
<a class="sourceLine" id="cb361-3" data-line-number="3">cov.xy<span class="op">/</span>sd.xy</a></code></pre></div>
<pre><code>## [1] -0.5884202</code></pre>
<p>The correlation coefficient for the variables is <span class="math inline">\(\approx\)</span> -0.59. The manual calculation is confirmed using the <code>cor()</code> function in R:</p>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb363-1" data-line-number="1"><span class="kw">cor</span>(ds.sub<span class="op">$</span>glbcc_risk, ds.sub<span class="op">$</span>ideol)</a></code></pre></div>
<pre><code>## [1] -0.5884202</code></pre>
<p><strong>Note:</strong> To calculate the correlation coefficient manually in one line of code:</p>
<p><code>sum((x-mean(x))*(y-mean(y))) /(sqrt(sum((x-mean(x))^2))*sqrt(sum((y-mean(y))^2)))</code></p>
</div>
<div id="correlation-tests" class="section level3">
<h3><span class="header-section-number">7.2.2</span> Correlation Tests</h3>
<p>The previous section demonstrated the <code>cor()</code> function to confirm the manual calculation of the correlation coefficient. Using this function we can find the correlation coefficient of the income and perceived risk variables:</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb365-1" data-line-number="1"><span class="kw">cor</span>(ds<span class="op">$</span>income, ds<span class="op">$</span>glbcc_risk, <span class="dt">use =</span> <span class="st">&quot;complete.obs&quot;</span>)</a></code></pre></div>
<pre><code>## [1] -0.05904785</code></pre>
<p>The correlation coefficient of -0.06 informs us of two things: the relationship is negative and very weak. <strong>Note:</strong> The correlation coefficient is drawn from observations within a sample, and therefore is a random value. That is, if we were to collect multiple samples we would calculate different correlation coefficients for each sample collected. This leads to a new hypothesis: is there a relationship between income and perceived risk? To test this we employ Pearson’s product-moment correlation available via the <code>cor.test()</code> function. Our testing hypotheses are:</p>
<p>-<span class="math inline">\(H_0\)</span>: the true correlation coefficient is zero<br />
-<span class="math inline">\(H_1\)</span>: the true correlation coefficient is not zero</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb367-1" data-line-number="1"><span class="kw">cor.test</span>(ds<span class="op">$</span>income, ds<span class="op">$</span>glbcc_risk, <span class="dt">use=</span><span class="st">&quot;complete.obs&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  ds$income and ds$glbcc_risk
## t = -2.83, df = 2289, p-value = 0.004695
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.09975880 -0.01813952
## sample estimates:
##         cor 
## -0.05904785</code></pre>
<p>The correlation test yields a p-value &lt; <span class="math inline">\(\alpha\)</span> = 0.05, thereby the null hypothesis is rejected such that the true correlation coefficient is not zero.</p>
<p><strong>Note:</strong> Despite rejecting the null hypothesis, our random correlation value is still quite small at -0.06. This indicates a very weak, or non-substance, relationship between income and perceived risk.</p>
<p>To demonstrate a potentially substantive relationship we look at ideology and perceived risk of climate change using the <code>cor.test()</code> function:</p>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb369-1" data-line-number="1"><span class="kw">cor.test</span>(ds<span class="op">$</span>ideol, ds<span class="op">$</span>glbcc_risk)</a></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  ds$ideol and ds$glbcc_risk
## t = -36.633, df = 2511, p-value &lt; 0.00000000000000022
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.6150780 -0.5640865
## sample estimates:
##        cor 
## -0.5901706</code></pre>
<p>The default correlation test method for the <code>cor.test()</code> function is the Pearson test. The Spearman test is required for ordinal data via the <code>method=&quot;spearman&quot;</code> argument within the <code>cor.test()</code> function. For calculation correlation with ordinal data.</p>
</div>
<div id="correlation-across-groups" class="section level3">
<h3><span class="header-section-number">7.2.3</span> Correlation Across Groups</h3>
<p>Suppose you are interested in correlations across multiple variables. The <code>cor()</code> function examines the correlation between each variable pair for an entire data set. As such, if you are interested in only the correlation for select variables then use the <code>select()</code> function and select your variablesof interest, then pipe them into the <code>cor()</code> function. Include <code>drop_na()</code>. To demonstrate using variables from the class data set:</p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb371-1" data-line-number="1">ds <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb371-2" data-line-number="2"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(glbcc_risk, ideol, income, age) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb371-3" data-line-number="3"><span class="st">  </span><span class="kw">drop_na</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb371-4" data-line-number="4"><span class="st">  </span><span class="kw">cor</span>()</a></code></pre></div>
<pre><code>##             glbcc_risk       ideol      income         age
## glbcc_risk  1.00000000 -0.59999737 -0.06079785 -0.06799270
## ideol      -0.59999737  1.00000000  0.03901982  0.08608048
## income     -0.06079785  0.03901982  1.00000000 -0.11761722
## age        -0.06799270  0.08608048 -0.11761722  1.00000000</code></pre>
<p>This resulting matrix provides the correlation coefficients for two variables at a time. The correlation coefficients are defined by the intercept of the row and columns corresponding to each variable.</p>
<p>Additionally, recalling that each correlation coefficient itself is a random value, a test is required for inference. The <code>corr.test()</code> provided by the <code>psych</code> package is an alternative to the <code>cor.test()</code> function previously used. The <code>corr.test()</code> function supports examining variable pairs simultaneously within a given data set. Use the <code>print()</code> function with the <code>short=FALSE</code> argument to view the complete test with confidence intervals and p-values.</p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb373-1" data-line-number="1">ds <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb373-2" data-line-number="2"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(glbcc_risk, ideol, income, age) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb373-3" data-line-number="3"><span class="st">  </span><span class="kw">drop_na</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb373-4" data-line-number="4"><span class="st">  </span>corr.test <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb373-5" data-line-number="5"><span class="st">  </span><span class="kw">print</span>(<span class="dt">short =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## Call:corr.test(x = .)
## Correlation matrix 
##            glbcc_risk ideol income   age
## glbcc_risk       1.00 -0.60  -0.06 -0.07
## ideol           -0.60  1.00   0.04  0.09
## income          -0.06  0.04   1.00 -0.12
## age             -0.07  0.09  -0.12  1.00
## Sample Size 
## [1] 2275
## Probability values (Entries above the diagonal are adjusted for multiple tests.) 
##            glbcc_risk ideol income age
## glbcc_risk          0  0.00   0.01   0
## ideol               0  0.00   0.06   0
## income              0  0.06   0.00   0
## age                 0  0.00   0.00   0
## 
##  Confidence intervals based upon normal theory.  To get bootstrapped values, try cor.ci
##             raw.lower raw.r raw.upper raw.p lower.adj upper.adj
## glbc_-ideol     -0.63 -0.60     -0.57  0.00     -0.63     -0.56
## glbc_-incom     -0.10 -0.06     -0.02  0.00     -0.11     -0.01
## glbc_-age       -0.11 -0.07     -0.03  0.00     -0.12     -0.02
## ideol-incom      0.00  0.04      0.08  0.06      0.00      0.08
## ideol-age        0.05  0.09      0.13  0.00      0.03      0.14
## incom-age       -0.16 -0.12     -0.08  0.00     -0.17     -0.06</code></pre>
</div>
</div>
<div id="visualizing-correlation" class="section level2">
<h2><span class="header-section-number">7.3</span> Visualizing Correlation</h2>
<p>The simplest form to visualize correlation is a scatter plot with a trend line.</p>
<p>We will review the relationship between ideology and perceived risk from climate change. Build the basic visualization by using <code>ggplot()</code> and the <code>geom_point</code> functions, with ideology on the x axis and perceived risk about climate change on the y axis. Use the <code>ds.sub</code> dataset, because we removed the missing values.</p>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb375-1" data-line-number="1"><span class="kw">ggplot</span>(ds.sub, <span class="kw">aes</span>(<span class="dt">x =</span> ideol, <span class="dt">y =</span> glbcc_risk)) <span class="op">+</span></a>
<a class="sourceLine" id="cb375-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">shape =</span> <span class="dv">1</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/6_vis-1.png" width="672" /></p>
<p>Notice how this doesn’t really make sense? This is because there are thousands of observations being placed on a discrete set of values. To get a better idea of the relationship, we can tell R to jitter the points. “Jittering” provides a tiny bit of white noise and variance to the values, so that we can see where there is high overlap of observations. This provides a better picture of the relationship. This time use the <code>geom_jitter</code> function instead of the <code>geom_point</code> function:</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb376-1" data-line-number="1"><span class="kw">ggplot</span>(ds.sub, <span class="kw">aes</span>(<span class="dt">x =</span> ideol, <span class="dt">y =</span> glbcc_risk)) <span class="op">+</span></a>
<a class="sourceLine" id="cb376-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">shape =</span> <span class="dv">1</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/6_vis2-1.png" width="672" /></p>
<p>Notice the apparent negative correlation. Verify this by checking the correlation:</p>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb377-1" data-line-number="1">ds <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb377-2" data-line-number="2"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(ideol, glbcc_risk) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb377-3" data-line-number="3"><span class="st">  </span><span class="kw">cor</span>(<span class="dt">use =</span> <span class="st">&quot;complete.obs&quot;</span>)</a></code></pre></div>
<pre><code>##                 ideol glbcc_risk
## ideol       1.0000000 -0.5901706
## glbcc_risk -0.5901706  1.0000000</code></pre>
<p>A trend line to the scatter plot helps to interpret directionality of a given variable pair. The next lab will further introduce trend lines, but for now we introduce it via the <code>geom_smooth()</code> function by including the <code>method=lm</code> argument. We also need to include <code>geom_point()</code> for each point.</p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb379-1" data-line-number="1"><span class="kw">ggplot</span>(ds.sub, <span class="kw">aes</span>(<span class="dt">x =</span> ideol, <span class="dt">y =</span> glbcc_risk)) <span class="op">+</span></a>
<a class="sourceLine" id="cb379-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">shape =</span> <span class="dv">1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb379-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm) <span class="op">+</span></a>
<a class="sourceLine" id="cb379-4" data-line-number="4"><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">shape =</span> <span class="dv">1</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/6_vis4-1.png" width="672" /></p>
<p>The ideology points can be differentiated by other variables, such as gender, to examine potential difference among gender by defining the <code>color</code> argument as follows:</p>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb380-1" data-line-number="1"><span class="kw">ggplot</span>(ds.sub, <span class="kw">aes</span>(<span class="dt">x =</span> ideol, <span class="dt">y =</span> glbcc_risk, <span class="dt">color =</span> f.gender)) <span class="op">+</span></a>
<a class="sourceLine" id="cb380-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">shape =</span> <span class="dv">1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb380-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm) <span class="op">+</span></a>
<a class="sourceLine" id="cb380-4" data-line-number="4"><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">shape =</span> <span class="dv">1</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/6_vis5-1.png" width="672" /></p>
<div id="another-example-political-party" class="section level3">
<h3><span class="header-section-number">7.3.1</span> Another Example: Political Party</h3>
<p>Let’s look at this relationship broken down by political party. Perhaps you wanted to see if the relationship looks different for Republicans and Democrats. We can first subset the data for Republicans and Democrats:</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb381-1" data-line-number="1">ds.dem &lt;-<span class="st"> </span><span class="kw">filter</span>(ds.sub, f.party<span class="fl">.2</span> <span class="op">==</span><span class="st"> &quot;Dem&quot;</span>)</a>
<a class="sourceLine" id="cb381-2" data-line-number="2">ds.rep &lt;-<span class="st"> </span><span class="kw">filter</span>(ds.sub, f.party<span class="fl">.2</span> <span class="op">==</span><span class="st"> &quot;Rep&quot;</span>)</a></code></pre></div>
<p>Next we investigate the correlation between ideology and perceived risk of climate change for Republicans and Democrats separately:</p>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb382-1" data-line-number="1"><span class="kw">cor.test</span>(ds.rep<span class="op">$</span>ideol, ds.rep<span class="op">$</span>glbcc_risk)</a></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  ds.rep$ideol and ds.rep$glbcc_risk
## t = -14.352, df = 1171, p-value &lt; 0.00000000000000022
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.4343892 -0.3369909
## sample estimates:
##        cor 
## -0.3867682</code></pre>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb384-1" data-line-number="1"><span class="kw">cor.test</span>(ds.dem<span class="op">$</span>ideol, ds.dem<span class="op">$</span>glbcc_risk)</a></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  ds.dem$ideol and ds.dem$glbcc_risk
## t = -13.977, df = 859, p-value &lt; 0.00000000000000022
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.4833657 -0.3744104
## sample estimates:
##        cor 
## -0.4304548</code></pre>
<p>The correlation coefficient is slightly more negative for Democrats.</p>
<p>To create a visualization that compares the two parties and the relationship between climate change risk and ideology, a few simple lines of code can get the job done. First filter the data to include Democrats and Republicans, select the variables of interest, drop NAs, pipe it all into <code>ggplot2</code>, then use <code>facet_wrap()</code> to create two visualizations, one for each party:</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb386-1" data-line-number="1">ds <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb386-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(f.party<span class="fl">.2</span> <span class="op">==</span><span class="st"> &quot;Dem&quot;</span> <span class="op">|</span><span class="st"> </span>f.party<span class="fl">.2</span> <span class="op">==</span><span class="st"> &quot;Rep&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb386-3" data-line-number="3"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(ideol, glbcc_risk, f.party<span class="fl">.2</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb386-4" data-line-number="4"><span class="st">  </span><span class="kw">na.omit</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb386-5" data-line-number="5"><span class="st">  </span><span class="kw">ggplot</span>(., <span class="kw">aes</span>(ideol, glbcc_risk)) <span class="op">+</span></a>
<a class="sourceLine" id="cb386-6" data-line-number="6"><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">shape =</span> <span class="dv">1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb386-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm) <span class="op">+</span></a>
<a class="sourceLine" id="cb386-8" data-line-number="8"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>f.party<span class="fl">.2</span>, <span class="dt">scales =</span> <span class="st">&quot;fixed&quot;</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/6_2vis.5-1.png" width="672" /></p>
</div>
<div id="one-more-visualization" class="section level3">
<h3><span class="header-section-number">7.3.2</span> One More Visualization</h3>
<p>We cap this lab off with creating one last visualization. First create a new subset of our data exclusive of all missing observations. Include variables for climate change risk and age.</p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb387-1" data-line-number="1">sub.ds &lt;-<span class="st"> </span><span class="kw">filter</span>(ds) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb387-2" data-line-number="2"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(<span class="st">&quot;glbcc_risk&quot;</span>, <span class="st">&quot;age&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb387-3" data-line-number="3"><span class="st">  </span><span class="kw">na.omit</span>()</a></code></pre></div>
<p>First we look at our age variable.</p>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb388-1" data-line-number="1"><span class="kw">describe</span>(sub.ds<span class="op">$</span>age)</a></code></pre></div>
<pre><code>##    vars    n  mean   sd median trimmed   mad min max range  skew kurtosis
## X1    1 2536 60.37 14.2     62   61.02 13.34  18  99    81 -0.39    -0.24
##      se
## X1 0.28</code></pre>
<p>Now find the correlation:</p>
<div class="sourceCode" id="cb390"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb390-1" data-line-number="1"><span class="kw">cor.test</span>(sub.ds<span class="op">$</span>glbcc_risk, sub.ds<span class="op">$</span>age)</a></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  sub.ds$glbcc_risk and sub.ds$age
## t = -3.6446, df = 2534, p-value = 0.0002732
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.11082410 -0.03338258
## sample estimates:
##         cor 
## -0.07221218</code></pre>
<p>There is a slight negative correlation. We can interpret this as indicating that younger people are slightly more concerned about climate change. Now we construct the visualization:</p>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb392-1" data-line-number="1"><span class="kw">ggplot</span>(sub.ds, <span class="kw">aes</span>(<span class="dt">y =</span> glbcc_risk, <span class="dt">x =</span> age)) <span class="op">+</span></a>
<a class="sourceLine" id="cb392-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">shape =</span> <span class="dv">20</span>, <span class="dt">color =</span> <span class="st">&quot;#e20000&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb392-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">shape =</span> <span class="dv">20</span>, <span class="dt">color =</span> <span class="st">&quot;#e20000&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb392-4" data-line-number="4"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm) <span class="op">+</span></a>
<a class="sourceLine" id="cb392-5" data-line-number="5"><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Age&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb392-6" data-line-number="6"><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Climate Change Risk&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb392-7" data-line-number="7"><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Age and Climate Change Risk&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb392-8" data-line-number="8"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks =</span> <span class="kw">c</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">10</span>),</a>
<a class="sourceLine" id="cb392-9" data-line-number="9">                     <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;0&quot;</span>,<span class="st">&quot;1&quot;</span>,<span class="st">&quot;2&quot;</span>, <span class="st">&quot;3&quot;</span>, <span class="st">&quot;4&quot;</span>, <span class="st">&quot;5&quot;</span>, <span class="st">&quot;6&quot;</span>, <span class="st">&quot;7&quot;</span>, <span class="st">&quot;8&quot;</span>, <span class="st">&quot;9&quot;</span>, <span class="st">&quot;10&quot;</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb392-10" data-line-number="10"><span class="st">  </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/6_2vis4-1.png" width="672" /></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="inference-for-two-populations.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="bivariate-linear-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["_main.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
